runtime: python310
service: limoneide-backend

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6

env_variables:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  CACHE_TTL: "300"
  MAX_CONCURRENT_REQUESTS: "100"

handlers:
  # 정적 파일 처리
  - url: /static
    static_dir: static
    secure: always

  # API 라우트
  - url: /api/.*
    script: auto
    secure: always

  # 메인 애플리케이션
  - url: /.*
    script: auto
    secure: always

inbound_services:
  - warmup

basic_scaling:
  max_instances: 10
  idle_timeout: 10m

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

beta_settings:
  cloud_sql_instances: "limoneide-project:us-central1:limoneide-sql"

vpc_access_connector:
  name: "projects/limoneide-project/locations/us-central1/connectors/limoneide-vpc" 